Add AutoSortItems
Dalamud-DailyRoutines/DailyRoutines.Localizations pull request #11
Opened 2024-12-21 17:35 UTC by TheDeathDragon

2024-12-23 04:40 UTC, AtmoOmen requested changes

2024-12-23 04:40 UTC, AtmoOmen commented on ChineseSimplified.json
> +    "AutoSortItemsTableTitle":"物品排序方式",
非标题或描述需要在模块内部名称和词条具体名称之间加连词符

2024-12-23 05:30 UTC, AtmoOmen requested changes
请先检索是否有相同词条, 优先使用已有词条组合, 并且尽量不要新建词条
对于同样组合的LOC，请拆分然后在代码里将其组合

2024-12-24 12:42 UTC, TheDeathDragon commented
老师，我刚才修改了，已经复用了翻译，

然后有一些基础的我没有使用模块前缀，因为我觉得后面可以给其他模块复用

2024-12-25 08:25 UTC, merged